name: 'Analyze Cucumber Report'
description: 'Reads a cucumber report and generates a split config file'
author: 'Mark Goho'
inputs:
  individual-reports-folder:
    required: false
    description: 'The folder containing the downloaded individual cucumber reports'
    default: 'individual-reports'
  output-report:
    required: false
    description: 'relative path to output report'
    default: 'cucumber-split-config.json'
  group-count:
    required: false
    description: 'The number of groups to split the cucumber reports into'
runs:
  using: 'node16'
  main: 'dist/index.js'
