name: 'Analyze Cucumber Report'
description: 'Reads a cucumber report and generates a split config file'
author: 'Mark Goho'
inputs:
  local-report:
    required: true
    description: 'relative path to cucumber report'
  output-report:
    required: false
    description: 'relative path to output report'
    default: 'local-cucumber-report.json'
runs:
  using: 'node16'
  main: 'dist/index.js'
